version: '2.3'

services:
  frontend:
    build: ./frontend
    depends_on:
      - api

  api:
    build: ./api
    volumes:
      - ./forms:/data/forms
      - ./output:/usr/src/app/static

  fhir:
    image: smartonfhir/hapi:r3