# Contact Aqeel Akber <aqeel@thaum.io> for production versions

version: '2.3'

services:
  api:
    depends_on:
      - fhir

  nginx:
    depends_on:
      - frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./letsencrypt_nginx/data/certbot/conf:/etc/letsencrypt

  certbot:
    volumes:
      - ./letsencrypt_nginx/data/certbot/conf:/etc/letsencrypt
      - ./letsencrypt_nginx/data/certbot/www:/var/www/certbot

  fhir:
    entrypoint: ["echo", "Service fhir disabled"]
